DROP TABLE UZYTKOWNIK CASCADE CONSTRAINTS;
DROP TABLE MATERIAL CASCADE CONSTRAINTS;
DROP TABLE PYTANIA CASCADE CONSTRAINTS;
DROP TABLE RANKING CASCADE CONSTRAINTS;
DROP TABLE PRZEDMIOT CASCADE CONSTRAINTS;

CREATE TABLE Uzytkownik(
ID NUMBER(6) CONSTRAINT USER_PK PRIMARY KEY,
NAZWA VARCHAR2(30) NOT NULL UNIQUE,
HASLO VARCHAR2(30) NOT NULL,
MAIL VARCHAR2(30) NOT NULL
);
CREATE TABLE PRZEDMIOT(
ID NUMBER(6) CONSTRAINT PRZEDMIOT_PK PRIMARY KEY,
NAZWA VARCHAR2(30) NOT NULL,
RODZAJ VARCHAR2(30) NOT NULL
);
CREATE TABLE MATERIAL(
ID NUMBER(6) CONSTRAINT MATERIAL_PK PRIMARY KEY,
MATERIAL VARCHAR2(4000)NOT NULL,
PRZEDMIOT_ID NUMBER(6)NOT NULL,
CONSTRAINT MATERIAL_PRZEDMIOT_FK FOREIGN KEY(PRZEDMIOT_ID) REFERENCES PRZEDMIOT(ID)
);
CREATE TABLE PYTANIA(
ID NUMBER(6) CONSTRAINT PYTANIA_PK PRIMARY KEY,
TRESC VARCHAR2(200)NULL,
PRZEDMIOT_ID NUMBER(6)NOT NULL,
CONSTRAINT PYTANIA_PRZEDMIOT_FK FOREIGN KEY(PRZEDMIOT_ID) REFERENCES PRZEDMIOT(ID),
ODP_A VARCHAR2(30)NOT NULL,
ODP_B VARCHAR2(30)NOT NULL,
ODP_C VARCHAR2(30)NOT NULL,
ODP_D VARCHAR2(30)NOT NULL,
ODP_O VARCHAR2(200)NOT NULL,
O_Z NUMBER(1)NOT NULL,
POPR_Z NUMBER(2)NOT NULL
);
CREATE TABLE Ranking(
ID NUMBER(6) CONSTRAINT RANIKNG_PK PRIMARY KEY,
PRZEDMIOT_ID NUMBER(6) NOT NULL,
CONSTRAINT RANIKNG_PRZEDMIOT_FK FOREIGN KEY(PRZEDMIOT_ID) REFERENCES PRZEDMIOT(ID),
UZYTKOWNIK_ID NUMBER(6),
CONSTRAINT RANKING_UZYTKOWNIK_FK FOREIGN KEY(UZYTKOWNIK_ID) REFERENCES UZYTKOWNIK(ID),
PUNKTY NUMBER(6)NULL,
DATA DATE
);

Insert into Uzytkownik values (1,'admin','admin','wut');
Insert into Uzytkownik values (2,'a','ad','wut');
INSERT INTO PRZEDMIOT values (1,'SYSTEMY OPERACYJNE','WYKLAD');
INSERT INTO przedmiot values (2,'SYSTEMY INFORMACYJNE','LABORATORIUM');
INSERT INTO MATERIAL VALUES (1,'ASDFF',1);
INSERT INTO MATERIAL VALUES (2,'wraezcwetdzsvxatsdzfxcvzfdstedzxvdtsxcxdstrxcbgrwesfjck cgfdgkfsodazcmkxvj jbfgdnsfeadzlmcx mvbndsfplzxmc bnsfjedmzl;cxcv nkdghrsfejdml;zcx, vmfds',2);
INSERT INTO PYTANIA VALUES (1,'A',1,'A','B','C','D','OTWARTE',1,1);
INSERT INTO PYTANIA VALUES (2,'A',2,'A','B','C','D','OTWARTE',2,2);
INSERT INTO RANKING VALUES (1,1,1,20,TO_DATE('2012-06-05', 'YYYY-MM-DD'));


